#!/bin/bash
# activate_vllm.sh — activate the vLLM environment for manual shell use
# Usage: source ~/thorllm/activate_vllm.sh
# Generated by thorllm.
# =============================================================================

# ── CUDA ──────────────────────────────────────────────────────────────────────
export CUDA_HOME="${CUDA_HOME}"
export TRITON_PTXAS_PATH="${CUDA_HOME}/bin/ptxas"
export TRITON_PTXAS_BLACKWELL_PATH="${TRITON_PTXAS_PATH}"
export TRITON_CUDART_PATH="${CUDA_HOME}/include"
export TRITON_CUDACRT_PATH="${CUDA_HOME}/include"
export TRITON_CUPTI_PATH="${CUDA_HOME}/include"
export TRITON_NVDISASM_PATH="${CUDA_HOME}/bin/nvdisasm"
export TRITON_CUOBJDUMP_PATH="${CUDA_HOME}/bin/cuobjdump"
export LIBRARY_PATH="${CUDA_HOME}/lib64/stubs:${LIBRARY_PATH:-}"
export PATH="${CUDA_HOME}/bin:${PATH}"
export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH:-}"
export TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH}"
export DG_JIT_USE_NVRTC=1

# ── vLLM runtime ─────────────────────────────────────────────────────────────
export VLLM_ENABLE_V1_MULTIPROCESSING=0
export VLLM_PLUGINS=""
export VLLM_LOGGING_LEVEL=INFO
export VLLM_NO_USAGE_STATS=1
export DO_NOT_TRACK=1
export PYTHONUNBUFFERED=1
export SAFETENSORS_FAST_GPU=1
export CUDA_VISIBLE_DEVICES=0
# NVFP4 / SM110 note:
#   Triton attention backend works fine on Thor.
#   If MoE throughput is unexpectedly low, try: export VLLM_USE_FLASHINFER_MOE_FP4=0

# ── Cache dirs ────────────────────────────────────────────────────────────────
export CACHE_ROOT="${CACHE_ROOT}"
export VLLM_CACHE_ROOT="${VLLM_CACHE_ROOT}"
export VLLM_ASSETS_CACHE="${VLLM_ASSETS_CACHE}"
export VLLM_TUNED_CONFIG_FOLDER="${VLLM_TUNED_CONFIG_FOLDER}"
export FLASHINFER_JIT_DIR="${FLASHINFER_JIT_DIR}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR}"
export TORCHINDUCTOR_CACHE_DIR="${TORCHINDUCTOR_CACHE_DIR}"
export TORCH_COMPILE_CACHE_DIR="${TORCH_COMPILE_CACHE_DIR}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME}"
export TIKTOKEN_CACHE_DIR="${TIKTOKEN_ENCODINGS_BASE}"
export TIKTOKEN_ENCODINGS_BASE="${TIKTOKEN_ENCODINGS_BASE}"
export TIKTOKEN_RS_CACHE_DIR="${TIKTOKEN_RS_CACHE_DIR}"

# ── Activate venv ─────────────────────────────────────────────────────────────
# shellcheck disable=SC1091
source "${VENV_PATH}/bin/activate"

echo "vLLM env active — $(python -c 'import vllm; print(vllm.__version__)' 2>/dev/null || echo 'not installed')"
echo "  Model: ${SERVE_MODEL}"
echo "  Cache: ${CACHE_ROOT}"
