#!/bin/bash
# vllm-serve.sh — vLLM launcher called by systemd
# Generated by thorllm. Do not edit paths — they are set at install time.
# To change the model:      edit SERVE_MODEL in ${BUILD_PATH}/vllm.env
# To change per-model args: edit ${MODELS_DIR}/<org>/<n>.yaml
# Then: sudo systemctl restart vllm
# =============================================================================
set -euo pipefail

VLLM_BIN="${VENV_PATH}/bin/vllm"
MODELS_DIR="${MODELS_DIR}"

# ── Resolve model config ──────────────────────────────────────────────────────
if [[ -z "${SERVE_MODEL:-}" ]]; then
    echo "[ERROR] SERVE_MODEL is not set. Check ${BUILD_PATH}/vllm.env" >&2
    exit 1
fi

MODEL_CONFIG="${MODELS_DIR}/${SERVE_MODEL}.yaml"

if [[ ! -f "${MODEL_CONFIG}" ]]; then
    echo "[ERROR] Model config not found: ${MODEL_CONFIG}" >&2
    echo "        Create it: thorllm model add ${SERVE_MODEL}" >&2
    exit 1
fi

# ── Drop page cache before loading model weights ──────────────────────────────
# Requires: ${SERVICE_USER} ALL=(root) NOPASSWD: /usr/bin/tee /proc/sys/vm/drop_caches
sync && echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null || true

# ── Launch ────────────────────────────────────────────────────────────────────
exec "${VLLM_BIN}" serve \
    --config "${MODEL_CONFIG}" \
    --max-num-seqs 4 \
    --cpu-offload-gb 0 \
    --host 0.0.0.0 \
    --disable-fastapi-docs \
    --enable-force-include-usage \
    --download-dir "${CACHE_ROOT}/huggingface"
